import React from 'react';
import { renderToString } from 'react-dom/server';
import { Provider } from 'react-redux';
import { StaticRouter } from 'react-router-dom';
import { ChunkExtractor } from '@loadable/server';
import { renderRoutes } from 'react-router-config';
import { ThemeProvider } from '@material-ui/core/styles';
import Routes from '../src/router/routes';
import theme from '../styles/theme';

const path = require('path');

export default (pathname, store, context) => {
  // This is the stats file generated by webpack loadable plugin
  const statsFile = path.resolve('dist/loadable-stats.json');

  // We create an extractor from the statsFile
  const extractor = new ChunkExtractor({ statsFile });

  const content = renderToString(
    extractor.collectChunks(
      <Provider store={store}>
        <ThemeProvider theme={theme}>
          <StaticRouter location={pathname} context={context}>
            {renderRoutes(Routes)}
          </StaticRouter>
        </ThemeProvider>
      </Provider>
    )
  );

  return `
  <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="description"
          content="React SSR"
        />
        <title>Title</title>
        ${extractor.getStyleTags()}
      </head>
      <body>

      <div id="app">${content}</div>
      <script>
        window.INITIAL_STATE = ${JSON.stringify(store.getState())}
      </script>
      ${extractor.getScriptTags()}
      </body>
      </html>
  `;
};
